### ISSUE TITLE
System command 'qgis_process' failed on mac-os, qgis LTR (problems with plugins Valhalla & Networks)

### ISSUE THREAD

**Issue by sriramab** [r-spatial/qgisprocess#179] opened 2023-09-24 19:30 UTC
Hi,

I am having problem running qgisprocess on mac-monterey intel machine and qgis LTR 3.28.8. 
I have read through some closed issues and checked that I have qgis installed in a standard path and also defined qgis_process path in options. But I am still not able to get it working. 

Please guide how to fix this problem.

Thank you.

```
R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

```

```
> options(qgisprocess.path = "/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process")
> library(qgisprocess)
Attempting to load the package cache ... No cache found.
Will try to reconfigure qgisprocess and build new cache ...

ATTENTION: the QGIS plugins could not be queried. You will loose some functionality.
You may want to (re)run `qgis_configure()`; see its documentation.
Error message was:
Error in "processx::run(path, args, ...)": ! System command 'qgis_process' failed


ATTENTION: the QGIS algorithms could not be queried. You will loose some functionality.
You may want to (re)run `qgis_configure()`; see its documentation.
Error message was:
Error in "processx::run(path, args, ...)": ! System command 'qgis_process' failed


>>> PROBLEM encountered: couldn't build and save package cache! <<<
The 'qgis_process' command-line utility was either not found or
did not fulfil the needs to build the package cache.
Please run `qgis_configure()` to fix this and rebuild the cache.
See its documentation if you need to preset the path of qgis_process.
If the problem persists, make sure that you correctly installed QGIS
for your operating system using the instructions at
<https://download.qgis.org>.
> qgis_configure()
Trying getOption('qgisprocess.path'): '/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process'
Success!
Now using 'qgis_process' at '/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process'.
>>> If you need another installed QGIS instance, run `qgis_configure()`;
    see `?qgis_configure` if you need to preset the path of 'qgis_process'.

QGIS version is now set to: 3.28.8-Firenze
Using JSON for output serialization.
Using JSON for input serialization.

ATTENTION: the QGIS plugins could not be queried. You will loose some functionality.
You may want to (re)run `qgis_configure()`; see its documentation.
Error message was:
Error in "processx::run(path, args, ...)": ! System command 'qgis_process' failed


ATTENTION: the QGIS algorithms could not be queried. You will loose some functionality.
You may want to (re)run `qgis_configure()`; see its documentation.
Error message was:
Error in "processx::run(path, args, ...)": ! System command 'qgis_process' failed


>>> PROBLEM encountered: couldn't build and save package cache! <<<
The 'qgis_process' command-line utility was either not found or
did not fulfil the needs to build the package cache.
Please run `qgis_configure()` to fix this and rebuild the cache.
See its documentation if you need to preset the path of qgis_process.
If the problem persists, make sure that you correctly installed QGIS
for your operating system using the instructions at
<https://download.qgis.org>.
>
```

**Comment by florisvdh** [comment] 2023-09-25 11:50
Thanks.

There appears to be a specific problem with the Valhalla plugin to use it with `qgis_process` (will be reported; I can reproduce that error too). That will have to be solved by the maintainer of Valhalla.

However you also get a segmentation fault, and this is probably the main cause of the problem.

First, to make sure. What happens after you _disable_ Valhalla in the QGIS GUI (Plugins > Manage & install plugins > Installed > uncheck the box of 'Valhalla') and then again run in R:

```r
qgis_configure()
qgis_run(args = c("plugins", "--json"))
```

**Comment by sriramab** [comment] 2023-09-25 12:07
Please see below:

```
> qgis_configure()
Trying getOption('qgisprocess.path'): '/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process'
Success!
Now using 'qgis_process' at '/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process'.
>>> If you need another installed QGIS instance, run `qgis_configure()`;
    see `?qgis_configure` if you need to preset the path of 'qgis_process'.

QGIS version is now set to: 3.28.8-Firenze
Using JSON for output serialization.
Using JSON for input serialization.

ATTENTION: the QGIS plugins could not be queried. You will loose some functionality.
You may want to (re)run `qgis_configure()`; see its documentation.
Error message was:
Error in "processx::run(path, args, ...)": ! System command 'qgis_process' failed


ATTENTION: the QGIS algorithms could not be queried. You will loose some functionality.
You may want to (re)run `qgis_configure()`; see its documentation.
Error message was:
Error in "processx::run(path, args, ...)": ! System command 'qgis_process' failed


>>> PROBLEM encountered: couldn't build and save package cache! <<<
The 'qgis_process' command-line utility was either not found or
did not fulfil the needs to build the package cache.
Please run `qgis_configure()` to fix this and rebuild the cache.
See its documentation if you need to preset the path of qgis_process.
If the problem persists, make sure that you correctly installed QGIS
for your operating system using the instructions at
<https://download.qgis.org>.

> qgis_run(args = c("plugins", "--json"))
Error in `processx::run(path, args, ...)`:
! System command 'qgis_process' failed
---
Exit status: 139
Stderr:
/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process: line 6: 46715 Segmentation fault: 11  $THISDIR/../qgis_process.app/Contents/MacOS/qgis_process "$@"
---
Type .Last.error to see the more details.
> 
```

**Comment by florisvdh** [comment] 2023-09-25 12:27
OK thank you. So the problem is with `qgis_process` indeed, regardless of Valhalla. Next step before reporting this to the QGIS developers, is to verify this problem in the current version of QGIS LTR, which is at 3.28.11. You still have version 3.28.8 which lacks several patches.

Can you install QGIS LTR 3.28.11 (https://qgis.org/en/site/forusers/download.html) and rerun the same two lines in R? If you still observe the problem, then it's an issue for QGIS (since 3.28.11 is supported) and in such case you could also verify it in QGIS 3.32 (that is the current version).

**Comment by florisvdh** [comment] 2023-09-25 12:28
The Valhalla problem has been reported: https://github.com/gis-ops/valhalla-qgis-plugin/issues/12.

**Comment by sriramab** [comment] 2023-09-25 19:24
please see, I get the same segmentation error with 3.28.11

```
> options(qgisprocess.path = "/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process")
> library(qgisprocess)
> qgis_version(query = TRUE, debug = TRUE)
[1] "3.28.11-Firenze"

Versions reported by 'qgis_process':
------------------------------------
QGIS 3.28.11-Firenze 'Firenze' (d1af706d752)
QGIS code revision d1af706d752
Qt version 5.15.2
Python version 3.9.5
GDAL/OGR version 3.3.2
PROJ version 8.1.1
EPSG Registry database version v10.028 (2021-07-07)
GEOS version 3.9.1-CAPI-1.14.2
SQLite version 3.35.2
OS macOS 12.6

> qgis_run(args = c("plugins", "--json"))
Error in `processx::run(path, args, ...)`:
! System command 'qgis_process' failed
---
Exit status: 139
Stderr:
/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process: line 6:  3154 Segmentation fault: 11  $THISDIR/../qgis_process.app/Contents/MacOS/qgis_process "$@"
---
Type .Last.error to see the more details.
>
```

**Comment by sriramab** [comment] 2023-09-25 19:51
I have the same eror also with QGIS 3.32 Lima

```
> #options(qgisprocess.path = "/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process")
> options(qgisprocess.path = "/Applications/QGIS.app/Contents/MacOS/bin/qgis_process")
> library(qgisprocess)
Attempting to load the package cache ... No cache found.
Will try to reconfigure qgisprocess and build new cache ...

ATTENTION: the QGIS plugins could not be queried. You will loose some functionality.
You may want to (re)run `qgis_configure()`; see its documentation.
Error message was:
Error in "processx::run(path, args, ...)": ! System command 'qgis_process' failed


ATTENTION: the QGIS algorithms could not be queried. You will loose some functionality.
You may want to (re)run `qgis_configure()`; see its documentation.
Error message was:
Error in "processx::run(path, args, ...)": ! System command 'qgis_process' failed


>>> PROBLEM encountered: couldn't build and save package cache! <<<
The 'qgis_process' command-line utility was either not found or
did not fulfil the needs to build the package cache.
Please run `qgis_configure()` to fix this and rebuild the cache.
See its documentation if you need to preset the path of qgis_process.
If the problem persists, make sure that you correctly installed QGIS
for your operating system using the instructions at
<https://download.qgis.org>.
> qgis_configure()
Trying getOption('qgisprocess.path'): '/Applications/QGIS.app/Contents/MacOS/bin/qgis_process'
Success!
Now using 'qgis_process' at '/Applications/QGIS.app/Contents/MacOS/bin/qgis_process'.
>>> If you need another installed QGIS instance, run `qgis_configure()`;
    see `?qgis_configure` if you need to preset the path of 'qgis_process'.

QGIS version is now set to: 3.32.3-Lima
Using JSON for output serialization.
Using JSON for input serialization.

ATTENTION: the QGIS plugins could not be queried. You will loose some functionality.
You may want to (re)run `qgis_configure()`; see its documentation.
Error message was:
Error in "processx::run(path, args, ...)": ! System command 'qgis_process' failed


ATTENTION: the QGIS algorithms could not be queried. You will loose some functionality.
You may want to (re)run `qgis_configure()`; see its documentation.
Error message was:
Error in "processx::run(path, args, ...)": ! System command 'qgis_process' failed


>>> PROBLEM encountered: couldn't build and save package cache! <<<
The 'qgis_process' command-line utility was either not found or
did not fulfil the needs to build the package cache.
Please run `qgis_configure()` to fix this and rebuild the cache.
See its documentation if you need to preset the path of qgis_process.
If the problem persists, make sure that you correctly installed QGIS
for your operating system using the instructions at
<https://download.qgis.org>.
> qgis_version(query = TRUE, debug = TRUE)
[1] "3.32.3-Lima"

Versions reported by 'qgis_process':
------------------------------------
QGIS 3.32.3-Lima 'Lima' (67d46100b5b)
QGIS code revision 67d46100b5b
Qt version 5.15.2
Python version 3.9.5
GDAL/OGR version 3.3.2
PROJ version 8.1.1
EPSG Registry database version v10.028 (2021-07-07)
GEOS version 3.9.1-CAPI-1.14.2
SQLite version 3.35.2
OS macOS 12.6

> qgis_run(args = c("plugins", "--json"))
Error in `processx::run(path, args, ...)`:
! System command 'qgis_process' failed
---
Exit status: 139
Stderr:
/Applications/QGIS.app/Contents/MacOS/bin/qgis_process: line 6:  5390 Segmentation fault: 11  $THISDIR/../qgis_process.app/Contents/MacOS/qgis_process "$@"
---
Type .Last.error to see the more details.
> 
```

**Comment by sriramab** [comment] 2023-09-25 19:53
and almost at run of each command I get this error

![image](https://github.com/r-spatial/qgisprocess/assets/12668606/43d3e5c1-68b6-4027-9d58-0cd662b2cec3)

**Comment by florisvdh** [comment] 2023-09-25 20:05
OK, thanks a lot for pursuing this @sriramab!

Does omitting the `--json` part make a difference?

`qgis_run(args = "plugins")`

**Comment by florisvdh** [comment] 2023-09-25 20:29
OK, thanks!

The only difference I can see with the macOS runner of GitHub Actions (where the macOS tests of {qgisprocess} are run), is the R version and platform version reported in your first post: `4.2.2` and `x86_64-apple-darwin17.0 (64-bit)`. But everything reported by `qgis_version(query = TRUE, debug = TRUE)` is exactly the same, so I'm puzzled why you get a segfault and why it does not happen in GHA.

From https://github.com/r-spatial/qgisprocess/actions/runs/6274028647/job/17038646539#step:22:15:

```r
R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin20 (64-bit)

> if (has_qgis()) qgis_version(debug = TRUE)
[1] "3.32.3-Lima"

Versions reported by 'qgis_process':
------------------------------------
QGIS 3.32.3-Lima 'Lima' (67d46100b5b)
QGIS code revision 67d46100b5b
Qt version 5.15.2
Python version 3.9.5
GDAL/OGR version 3.3.2
PROJ version 8.1.1
EPSG Registry database version v10.028 (2021-07-07)
GEOS version 3.9.1-CAPI-1.14.2
SQLite version 3.35.2
OS macOS 12.6
```

If you're prepared to report this in the QGIS repo (https://github.com/qgis/QGIS/issues/new/choose), then reduce the issue to running `qgis_process plugins --json` or `qgis_process plugins` in a terminal (provided that `qgis_process` is in the PATH, otherwise use its full filepath), since this is not R-specific.

Hence make a reproducible shell script + output like below, but of course substituting with the output you get:

```bash
$ qgis_process plugins
Available plugins
(* indicates loaded plugins which implement Processing providers)

* QNEAT3
* valhalla
* processing_saga_nextgen
* pcraster_tools
* ViewshedAnalysis
* cartography_tools
* wbt_for_qgis
* latlontools
* grassprovider
* otbprovider
* processing
$ 
$ qgis_process list | head
Available algorithms

QGIS (3D)
	3d:tessellate	Tessellate

Valhalla
	Valhalla:directions_from_point_layer_auto	Directions From Point Layer Auto
	Valhalla:directions_from_point_layer_bicycle	Directions From Point Layer Bicycle
	Valhalla:directions_from_point_layer_pedestrian	Directions From Point Layer Pedestrian
	Valhalla:directions_from_point_layer_truck	Directions From Point Layer Truck
$ 
$ qgis_process --version
QGIS 3.32.3-Lima 'Lima' (67d46100b5)
QGIS code revision 67d46100b5
Qt version 5.15.3
Python version 3.10.12
GDAL/OGR version 3.6.4
PROJ version 9.1.1
EPSG Registry database version v10.076 (2022-08-31)
GEOS version 3.11.1-CAPI-1.17.1
SQLite version 3.37.2
OS Linux Mint 21.2
```

(I usually take the last part (version) to provide the QGIS version in the corresponding field of the issue)

The `qgis_process plugins` and `qgis_process list` commands are the commands run from R to get the list of plugins and algorithms, respectively; although by default this is appended with `--json` to get the result as a JSON string.

This problem will have to be sorted out for you by QGIS in order to get R package {qgisprocess} working with algorithms on your machine. Maybe there's interaction with some general setting on your system, explaining why this does not necessarily happen on macOS, but also if that's true it should not happen anyway.

If you're not going to post the issue, I can do it for you, if you provide the output of above commands. The best is that you do it though, so that they can directly interact with you to get more info about your system as needed.

**Comment by florisvdh** [comment] 2023-09-25 20:30
And as you can tell from my output above, the Valhalla plugin now works (it's been fixed by the developer already, so should normally be pushed to the QGIS plugin repo soon).

**Comment by florisvdh** [comment] 2023-09-25 20:35
Well, that makes me make another guess...

Perhaps you can try to disable all enabled plugins, and see whether that solves problems. If so, it must be another plugin causing the problem. I'm saying this because you _did get_ an error 'error starting plugin: valhalla' which means `qgis_process plugins` was doing stuff before stopping.

You could try: `qgis_disable_plugins()` (that should disable all enabled plugins). If it errors, just uncheck all plugins in the QGIS GUI and run `qgis_configure()` again in R.

Not that I have too much hope in this, but better to check that too.

**Comment by sriramab** [comment] 2023-09-26 18:36
Thank you. It seems to be working when I unchecked all plugins in GUI. The output is as follows. Please check, if this is how it should be. Never used it before so not sure how it should be. I only see no error. 
```
> options(qgisprocess.path = "/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process")
> library(qgisprocess)
Attempting to load the package cache ... No cache found.
Will try to reconfigure qgisprocess and build new cache ...
QGIS version: 3.28.11-Firenze
Having access to 350 algorithms from 5 QGIS processing providers.
Run `qgis_configure(use_cached_data = TRUE)` to reload cache and get more details.
>>> Run `qgis_enable_plugins()` to enable 10 disabled plugins and access their algorithms: DataPlotly, QuickOSM, grassprovider, kmltools, network_gt, networks,
    otbprovider, processing_r, processing_saga_nextgen, sagaprovider
> qgis_configure(use_cached_data = TRUE)
Checking configuration in cache file (/Users/srirama/Library/Caches/R-qgisprocess/cache-0.1.0.9177.rds)
Checking cached QGIS version with version reported by '/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process' ...
QGIS versions match! (3.28.11-Firenze)
Checking cached QGIS plugins (and state) with those reported by '/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process' ...
QGIS plugins match! (1 processing provider plugin(s) enabled)

>>> Run `qgis_enable_plugins()` to enable 10 disabled plugins and access their algorithms: DataPlotly, QuickOSM, grassprovider, kmltools, network_gt, networks,
    otbprovider, processing_r, processing_saga_nextgen, sagaprovider

Restoring configuration from '/Users/srirama/Library/Caches/R-qgisprocess/cache-0.1.0.9177.rds'
QGIS version: 3.28.11-Firenze
Using 'qgis_process' at '/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process'.
>>> If you need another installed QGIS instance, run `qgis_configure()`;
    see `?qgis_configure` if you need to preset the path of 'qgis_process'.
Using JSON for output serialization.
Using JSON for input serialization.
1 out of 11 available processing provider plugins are enabled.
Having access to 350 algorithms from 5 QGIS processing providers.
Use qgis_algorithms(), qgis_providers(), qgis_plugins(), qgis_using_json_output(),
qgis_path() and qgis_version() to inspect the cache environment.
> qgis_algorithms()
# A tibble: 350 × 24
   provider provider_title algorithm          algorithm_id algorithm_title provider_can_be_acti…¹ provider_is_active provider_long_name provider_version provider_warning can_cancel
   <chr>    <chr>          <chr>              <chr>        <chr>           <lgl>                  <lgl>              <chr>              <chr>            <chr>            <lgl>     
 1 3d       QGIS (3D)      3d:tessellate      tessellate   Tessellate      TRUE                   TRUE               QGIS (3D)          NA               NA               TRUE      
 2 gdal     GDAL           gdal:aspect        aspect       Aspect          TRUE                   TRUE               GDAL (3.3.2)       NA               NA               TRUE      
 3 gdal     GDAL           gdal:assignprojec… assignproje… Assign project… TRUE                   TRUE               GDAL (3.3.2)       NA               NA               TRUE      
 4 gdal     GDAL           gdal:buffervectors buffervecto… Buffer vectors  TRUE                   TRUE               GDAL (3.3.2)       NA               NA               TRUE      
 5 gdal     GDAL           gdal:buildvirtual… buildvirtua… Build virtual … TRUE                   TRUE               GDAL (3.3.2)       NA               NA               TRUE      
 6 gdal     GDAL           gdal:buildvirtual… buildvirtua… Build virtual … TRUE                   TRUE               GDAL (3.3.2)       NA               NA               TRUE      
 7 gdal     GDAL           gdal:cliprasterby… cliprasterb… Clip raster by… TRUE                   TRUE               GDAL (3.3.2)       NA               NA               TRUE      
 8 gdal     GDAL           gdal:cliprasterby… cliprasterb… Clip raster by… TRUE                   TRUE               GDAL (3.3.2)       NA               NA               TRUE      
 9 gdal     GDAL           gdal:clipvectorby… clipvectorb… Clip vector by… TRUE                   TRUE               GDAL (3.3.2)       NA               NA               TRUE      
10 gdal     GDAL           gdal:clipvectorby… clipvectorb… Clip vector by… TRUE                   TRUE               GDAL (3.3.2)       NA               NA               FALSE     
# ℹ 340 more rows
# ℹ abbreviated name: ¹​provider_can_be_activated
# ℹ 13 more variables: deprecated <lgl>, group <chr>, has_known_issues <lgl>, help_url <chr>, requires_matching_crs <lgl>, short_description <chr>, tags <list>,
#   default_raster_file_extension <chr>, default_vector_file_extension <chr>, supported_output_raster_extensions <list>, supported_output_table_extensions <list>,
#   supported_output_vector_extensions <list>, supports_non_file_based_output <lgl>
# ℹ Use `print(n = ...)` to see more rows
> qgis_providers()
# A tibble: 5 × 3
  provider provider_title    algorithm_count
  <chr>    <chr>                       <int>
1 gdal     GDAL                           56
2 model    Models                          1
3 qgis     QGIS                           50
4 3d       QGIS (3D)                       1
5 native   QGIS (native c++)             242
> qgis_plugins()
# A tibble: 11 × 2
   name                    enabled
   <chr>                   <lgl>  
 1 DataPlotly              FALSE  
 2 QuickOSM                FALSE  
 3 grassprovider           FALSE  
 4 kmltools                FALSE  
 5 network_gt              FALSE  
 6 networks                FALSE  
 7 otbprovider             FALSE  
 8 processing              TRUE   
 9 processing_r            FALSE  
10 processing_saga_nextgen FALSE  
11 sagaprovider            FALSE  
> qgis_using_json_output()
[1] TRUE
> qgis_path()
[1] "/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process"
> qgis_version()
[1] "3.28.11-Firenze"
```

**Comment by florisvdh** [comment] 2023-09-27 09:55
Thanks for the follow-up @sriramab. Yes! The R package is now functional, all output is as it should be :+1: . Of course without access to the processing plugins (see below). Too bad that I didn't think earlier of this, but I'm learning from it, so our journey will help future users as well!

So this will not lead to an issue at QGIS, but probably to at least one other plugin issue.

I suggest the following now:

1. First reinstall {qgisprocess}, it is now at 0.1.0.9178 (`remotes::install_github("r-spatial/qgisprocess")`). Error messages should be improved by also including the error message from `qgis_process`. This avoids the need for manual `qgis_run()` statements to get that.
2. Enable plugins from the R session. You could begin by enabling them all at once by just running `qgis_enable_plugins()` since messages should make clear where it errors (I suspect it will happen, but I'm not even sure). As you might end up in a state where {qgisprocess} doesn't load successfully, you may need to disable the specific plugin in QGIS (in case it got enabled indeed) and run `qgis_configure()` to get things working great again.
3. Some possible scenarios:
    - If you can see which plugin is the problem because it gave an error in step 2 (maybe you'll encounter this more than once), it may be that the process will have stopped and not enabled the remaining plugins. In that case, and after having applied the fixes described in step 2 if needed (disabling problematic plugin), proceed by enabling the remaining plugins but you will have to provide their names as a character vector to `qgis_enable_plugins()` in order to exclude the problematic plugin and prevent it from stopping the process.
    - Maybe step 2 apparently just succeeds and enables all plugins, but the subsequent reconfiguration that it triggers will then pop up with the segfault again, ending up in a badly configured state again. The remedy for that is as before (disabling all plugins in QGIS + rerunning `qgis_configure()`), and in this case you will have to run `qgis_enable_plugins()` for each plugin in turn, in order to observe at which stage things go wrong. As each `qgis_enable_plugins()` call triggers a reconfiguration (provided that it gets at that point), there's no need to run `qgis_configure()` in between. You could also try to script this process in a `for` loop, looping over `qgis_plugins(which = "disabled")$name` and adding some messages in that loop.

With the above hints I think you will be able to detect the plugin(s) that should not be enabled (hence need a fix) in order to get good behaviour. Maybe you'll need some retries here and there to get good control over it.

I'm looking forward to your findings! The more processing provider plugins we get in good shape for `qgis_process`, the more processing algorithms will become available in R.

BTW I've seen that the new version of Valhalla is present in the QGIS plugin repo, so you should also be able to just install the fixed version as usual in QGIS.

**Comment by sriramab** [comment] 2023-09-28 19:29
thank you @florisvdh . The process seems to be working and following are my observations:

1. networks plugin is failing the test https://github.com/crocovert/networks/
2. Once a plugin fails, all further qgis_enable_plugin() fail in the same R session. 

I am also getting SAGA error. Would you know how to fix it ?

```
> pq <- c("DataPlotly", "QuickOSM","grassprovider","kmltools","network_gt","processing","processing_r","processing_saga_nextgen" ,"sagaprovider"   )
> qgis_enable_plugins(names = pq)
Ignoring plugins that are enabled already: network_gt, processing, processing_r
Trying to enable following plugin(s): DataPlotly, QuickOSM, grassprovider, kmltools, processing_saga_nextgen, sagaprovider
DataPlotly successfully enabled!
QuickOSM successfully enabled!
grassprovider successfully enabled!
kmltools successfully enabled!
processing_saga_nextgen successfully enabled!
sagaprovider successfully enabled!

Rebuilding cache to reflect current plugin state ...

Trying getOption('qgisprocess.path'): '/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process'
Success!
Now using 'qgis_process' at '/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process'.
>>> If you need another installed QGIS instance, run `qgis_configure()`;
    see `?qgis_configure` if you need to preset the path of 'qgis_process'.

QGIS version is now set to: 3.28.11-Firenze
Using JSON for output serialization.
Using JSON for input serialization.
7 out of 11 available processing provider plugins are enabled.

Standard error message emitted by the 'qgis_process' command (non-fatal at this stage):
Problem with SAGA installation: unsupported SAGA version (found: 7.8.2, required: >=9.1.).


You now have access to 1625 algorithms from 11 QGIS processing providers.

>>> Run `qgis_enable_plugins()` to enable 4 disabled plugins and access their algorithms: network_gt, networks, otbprovider, processing_r

Saving configuration to '/Users/srirama/Library/Caches/R-qgisprocess/cache-0.1.0.9178.rds'
Use qgis_algorithms(), qgis_providers(), qgis_plugins(), qgis_using_json_output(),
qgis_path() and qgis_version() to inspect the cache environment.

```

**Comment by florisvdh** [comment] 2023-09-29 09:16
Excellent job, thanks!

I installed `networks`, tested it with the `qgis_process` CLI executable and it segfaults. So that's the plugin problem we expected! I'll follow up on it and link here.

Apart from `networks` can the remaining plugins be enabled? E.g. by excluding `networks` from the vector and rerunning your code. (Although `processing_r` may be rather unneeded since you're already in an R environment)

At least they work here:

```r
> qgis_enable_plugins(c("network_gt", "processing_r", "otbprovider"))
Trying to enable following plugin(s): network_gt, processing_r, otbprovider
network_gt successfully enabled!
processing_r successfully enabled!
otbprovider successfully enabled!

Rebuilding cache to reflect current plugin state ...

getOption('qgisprocess.path') was not found.
Sys.getenv('R_QGISPROCESS_PATH') was not found.
Trying 'qgis_process' on PATH...
Success!
Now using 'qgis_process' in the system PATH.
>>> If you need another installed QGIS instance, run `qgis_configure()`;
    see `?qgis_configure` if you need to preset the path of 'qgis_process'.

QGIS version is now set to: 3.32.3-Lima
Using JSON for output serialization.
Using JSON for input serialization.
13 out of 14 available processing provider plugins are enabled.
You now have access to 2087 algorithms from 17 QGIS processing providers.

>>> Run `qgis_enable_plugins()` to enable 1 disabled plugin and access
    its algorithms: networks

Saving configuration to '/home/floris/.cache/R-qgisprocess/cache-0.1.0.9178.rds'
Use qgis_algorithms(), qgis_providers(), qgis_plugins(), qgis_using_json_output(),
qgis_path() and qgis_version() to inspect the cache environment.
```

The SAGA error is related to the recent 'Processing Saga NextGen' plugin update (1.0.0), and is under consideration (https://github.com/north-road/qgis-processing-saga-nextgen/issues/34). It is what it says. Either upgrade your SAGA installation to its current release (https://sourceforge.net/projects/saga-gis/files/SAGA%20-%209/), or manually downgrade the QGIS plugin to its previous version 0.0.7, which can be downloaded as a zip-file from https://plugins.qgis.org/plugins/processing_saga_nextgen/version/0.0.7/ and installed in the QGIS GUI (I'd remove its existing install first and then install it anew from the file).

**Comment by sriramab** [comment] 2023-09-29 19:07
Hi @florisvdh , I can confirm that all other plugins can be enabled as a vector when networks is excluded.

**Comment by florisvdh** [comment] 2023-10-02 09:59
Networks issue reported at https://github.com/crocovert/networks/issues/15.

**Comment by florisvdh** [comment] 2023-10-02 10:02
> BTW I have no access to a macOS installation (apart from non-interactive session in GitHub Actions), but you're providing a good hint to improve the `qgis_detect_macos_paths()` function by the path you provide in `options()`. If you feel comfortable enough with R and git, you're also welcome to propose an update yourself of this (quite simple) function, to make it also work for your setup (it's in `R/qgis-detect.R`). `qgis_detect_macos_paths()` is run in the background when running `qgis_configure()` if the `qgisprocess.path` option is not set. Of course you can do this later once the issue is sorted out.

_Originally posted by @florisvdh in https://github.com/r-spatial/qgisprocess/issues/179#issuecomment-1733078389_

@sriramab would you be interested in making a pull request that improves the detection of `qgis_process` on macOS?

**Comment by sriramab** [comment] 2023-10-02 14:37
Hi @florisvdh , I would like to give PRa shot, but to be clear... I do not see what needs to be changed. You are reading all possible QGIS paths in qgis_detect_macos_paths(), and it looks correct to me. You would pickup both LTR and current versions from that function and append it with `Contents/MacOS/bin/qgis_process`. Which seems correct to me. So what will change?

**Comment by florisvdh** [comment] 2023-10-02 14:44
Ah OK, thanks for looking into it. So `library(qgisprocess)` is also successful if you drop `options(qgisprocess.path = "/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process")` from your scripts? Then indeed nothing needs changes.

**Comment by sriramab** [comment] 2023-10-02 18:45
Yes, please see. First it does not find it. Then if you `qgis_configure`, then it finds both LTR and current (in my case). And it choses the first found path as the path variable. So I guess it works without setting the path. 

```
> library(qgisprocess)
Attempting to load the package cache ... Success!
QGIS version: 3.28.11-Firenze
Having access to 350 algorithms from 5 QGIS processing providers.
Run `qgis_configure(use_cached_data = TRUE)` to reload cache and get more details.
>>> Run `qgis_enable_plugins()` to enable 11 disabled plugins and access their algorithms: DataPlotly, QuickOSM, grassprovider, kmltools, network_gt, networks,
    otbprovider, processing_r, processing_saga_nextgen, sagaprovider, valhalla


> qgis_configure()
getOption('qgisprocess.path') was not found.
Sys.getenv('R_QGISPROCESS_PATH') was not found.
Trying 'qgis_process' on PATH...
'qgis_process' is not available on PATH.
Found 2 QGIS installations containing 'qgis_process':
 /Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process
/Applications/QGIS.app/Contents/MacOS/bin/qgis_process
Trying command '/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process'
Success!
**Now using 'qgis_process' at '/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process'.**
>>> If you need another installed QGIS instance, run `qgis_configure()`;
    see `?qgis_configure` if you need to preset the path of 'qgis_process'.

QGIS version is now set to: 3.28.11-Firenze
Using JSON for output serialization.
Using JSON for input serialization.
1 out of 12 available processing provider plugins are enabled.
You now have access to 350 algorithms from 5 QGIS processing providers.

>>> Run `qgis_enable_plugins()` to enable 11 disabled plugins and access their algorithms: DataPlotly, QuickOSM, grassprovider, kmltools, network_gt, networks,
    otbprovider, processing_r, processing_saga_nextgen, sagaprovider, valhalla

Saving configuration to '/Users/srirama/Library/Caches/R-qgisprocess/cache-0.1.0.9178.rds'
Use qgis_algorithms(), qgis_providers(), qgis_plugins(), qgis_using_json_output(),
qgis_path() and qgis_version() to inspect the cache environment.

```

**Comment by florisvdh** [comment] 2023-10-03 07:31
OK, thanks.

> First it does not find it.

Rather: it does not _search_ when running `library(qgisprocess)` given that the package cache is OK. It already knew about the LTR as its path was stored in the package cache (it is verified though, at startup). That's why it reports `QGIS version: 3.28.11-Firenze` when running `library(qgisprocess)`.

`qgis_configure()` with default argument settings rebuilds the cache, so there indeed it searches and finds it (and rewrites this in the package cache). This proves that you don't need the `options(qgisprocess.path = )` and indeed no changes needed in `qgis_detect_macos_paths()`.

This issue can be closed once the Networks plugin is fixed.

Thanks for all the feedback!

**Comment by florisvdh** [comment] 2023-10-06 15:38
The Networks plugin has been fixed now! So you can upgrade the plugin in the QGIS GUI and then run `qgis_enable_plugins()` in R to get everything up and running. (On my system it works)

**Comment by sriramab** [comment] 2023-10-06 15:42
I will try it as soon as it becomes available to install from QGIS. thank you.

**Comment by florisvdh** [comment] 2023-10-06 15:43
It is available (see tab 'Versions' at https://plugins.qgis.org/plugins/networks/). Restart QGIS, or in Manage plugins, go to Settings and click 'reload repository' (or so).

**Comment by sriramab** [comment] 2023-10-06 18:32
@florisvdh . Thank you. It works. I will now go ahead with my experiments. Thank you.

**Closed** 2023-10-06 18:33 UTC
Labels: provider

**Comment by benz0li** [comment] 2023-10-08 08:40
ℹ️ You may be interested in the `qgisprocess` image of my 'Debian 12'-based, multi-arch (`linux/amd64`, `linux/arm64`) [JupyterLab R docker stack](https://github.com/b-data/jupyterlab-r-docker-stack) or [Data Science Dev Containers](https://github.com/b-data/data-science-devcontainers).

Cross reference: https://github.com/north-road/qgis-processing-saga-nextgen/issues/34#issuecomment-1751952598

FYI @Robinlovelace

**Comment by idshklein** [comment] 2024-11-12 18:49
I have the same problem with whitebox 1.1.1
output of qgis_process-qgis-ltr -v: 

QGIS 3.34.12-Prizren 'Prizren' (eeb6af3638)
QGIS code revision eeb6af3638
Qt version 5.15.13
Python version 3.12.7
GDAL/OGR version 3.9.3
PROJ version 9.5.0
EPSG Registry database version v11.016 (2024-08-31)
GEOS version 3.13.0-CAPI-1.19.0
SQLite version 3.46.1
OS Windows 11 Version 2009
