### ISSUE TITLE
JSON Error on qgis_configure

### ISSUE THREAD

**Issue by asitemade4u** [r-spatial/qgisprocess#176] opened 2023-09-18 22:25 UTC
Hi,

- I am using Ubuntu 20.x
- I installed the last version of QGis from the unstable branch. For now, I have left the installation as is, e.g. I have installed no QGis plugin
- I installed the last version of R
- I installed the last stable version of `qgisprocess`

When I execute `qgisprocess::qgis_configure()`, I get this message then the error:

```bash
GIS version is now set to: 3.26.3-Buenos
Using JSON for output serialization.
Using JSON for input serialization.
1 out of 4 available processing provider plugins are enabled.
parse error: premature EOF
                                       {   "gdal_version": "3.4.3",   
                     (right here) ------^
```

Please help,
S.

**Comment by florisvdh** [comment] 2023-09-20 14:13
Thank you!

> `qgis_version(debug = TRUE)` generates this error:

Try to rerun as:

`qgis_version(query = TRUE, debug = TRUE)`

**Comment by florisvdh** [comment] 2023-09-20 14:24
And this?

`qgis_query_path(quiet = FALSE)`

**Comment by florisvdh** [comment] 2023-09-20 14:33
Also if you restart R?

**Comment by florisvdh** [comment] 2023-09-20 14:40
OK thanks. Then let's go the terminal to check things with QGIS first. Can you run:

```
qgis --version
which qgis
which qgis_process
qgis_process --version
```

**Comment by florisvdh** [comment] 2023-09-20 14:43
Try:

`QT_QPA_PLATFORM = "offscreen" qgis_process --version`

**Comment by florisvdh** [comment] 2023-09-20 14:44
`QT_QPA_PLATFORM="offscreen" qgis_process --version`

**Comment by florisvdh** [comment] 2023-09-20 14:50
Does this work too ?

`QT_QPA_PLATFORM="offscreen" qgis_process list --json | wc -l`

**Comment by florisvdh** [comment] 2023-09-20 15:01
In a _new_ R session, can you run `library(qgisprocess)`, and after that run `ls.str(envir = qgisprocess:::qgisprocess_cache)`. Please paste the entire output here. If you like you can collapse lengthy outputs inside a `<details>` HTML tag, like:


    <details><summary>Title</summary>
    
    ```r
    Some code
    #> Some output
    ```
    
    </details>

</code>

Which gives:

<details><summary>Title</summary>

```r
Some code
#> Some output
```

</details>

**Comment by florisvdh** [comment] 2023-09-20 15:06
BTW if you want to get rid of the XDG_RUNTIME_DIR warning, have a look at https://stackoverflow.com/questions/59790350

**Comment by florisvdh** [comment] 2023-09-20 15:08
Thanks. What did `library(qgisprocess)` output before that?

BTW a typical output would be (ignore the fact I'm using a locally built QGIS here):

```r
> library(qgisprocess)
Attempting to load the package cache ... Success!
QGIS version: 3.33.0-Master, development state 4e83c82a
Having access to 1973 algorithms from 14 QGIS processing providers.
Run `qgis_configure(use_cached_data = TRUE)` to reload cache and get more details.
> ls.str(envir = qgisprocess:::qgisprocess_cache)
algorithms : tibble [1,973 × 24] (S3: tbl_df/tbl/data.frame)
loaded_from :  chr "/home/floris/.cache/R-qgisprocess/cache-0.1.0.rds"
path :  chr "/home/floris/git_repositories2/QGIS/build-4e83c82a/output/bin/qgis_process"
plugins : tibble [10 × 2] (S3: tbl_df/tbl/data.frame)
use_json_output :  logi TRUE
version :  chr "3.33.0-Master, development state 4e83c82a"
```

**Comment by florisvdh** [comment] 2023-09-20 15:12
> when I execute library(qgisprocess) it does not say anything...

Probably because it was loaded already. First restart R, then it should say something.

**Comment by florisvdh** [comment] 2023-09-20 15:16
> And when I tried to `qgis_configure()` I got the exact same output as before....

Please paste the output anyway, there have been several. I.e. does it report a QGIS version for example?

**Comment by florisvdh** [comment] 2023-09-20 15:17
Thanks. Do you get a different result for `ls.str(envir = qgisprocess:::qgisprocess_cache)` at this stage, or still all `NULL`?

**Comment by florisvdh** [comment] 2023-09-20 15:25
> Still a series of `NULL`

OK, that's because the function is interrupted; environment is then set back to the original state (with `NULL`s) it appears. At least it _was_ able to speak to `qgis_process` (as the **version** & **plugins** reading did work), only it was interrupted during what seems indeed a JSON parsing error – perhaps somehow linked to your environment. That's something to look closer at.

> algorithms :  NULL
loaded_from :  NULL
path :  NULL
plugins :  NULL
use_json_output :  NULL
version :  NULL

The fact that `path` is `NULL`, makes `qgis_run()` unable to access the `qgis_process` command in the shell, which explains all erros `argument is of length zero` you get from this point on. All functions that need the `qgis_process` backend go through `qgis_run()`, which itself uses the `path` value from the above `qgisprocess_cache` environment.

We just need to get the algorithm parsing working. I'll provide some R code.

**Comment by florisvdh** [comment] 2023-09-20 15:28
> On a hunch: When I execute `qgis_process` from VS Code terminal set to `bash` (not from R), I get this error:
> 
> ```shell
> qt.qpa.xcb: could not connect to display 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
> 
> Aborted
> ```
> 
> Don't you thing that could be the cause of all errors?

No because `qgis_run()` does prepend `QT_QPA_PLATFORM="offscreen"`. Otherwise you would never have seen things like:

```
QGIS version is now set to: 3.26.3-Buenos
1 out of 4 available processing provider plugins are enabled.
```

To return these two lines, `qgis_run()` was functioning well; the cache environment just screwed up in the next `qgis_algorithms()` step (I think).

**Comment by florisvdh** [comment] 2023-09-20 15:49
I think this will reproduce the error in your case, can you check? It does not use any {qgisprocess} function anymore (hence no need to load {qgisprocess}), but it is what `qgis_algorithms(query = TRUE)` does call, through `qgis_run()`.

``` r
result <- withr::with_envvar(
  c(QT_QPA_PLATFORM="offscreen"), 
  processx::run("qgis_process", c("list", "--json"), encoding = "UTF-8")
)
str(result)
#> List of 4
#>  $ status : int 0
#>  $ stdout : chr "{\n  \"gdal_version\": \"3.6.4\",\n  \"geos_version\": \"3.11.1-CAPI-1.17.1\",\n  \"proj_version\": \"Rel. 9.1."| __truncated__
#>  $ stderr : chr ""
#>  $ timeout: logi FALSE
```

<sup>Created on 2023-09-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.1 (2023-06-16)
#>  os       Linux Mint 21.2
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language nl_BE:nl
#>  collate  nl_BE.UTF-8
#>  ctype    nl_BE.UTF-8
#>  tz       Europe/Brussels
#>  date     2023-09-20
#>  pandoc   3.1.1 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.1   2023-03-23 [3] RSPM (R 4.2.0)
#>  digest        0.6.33  2023-07-07 [3] RSPM (R 4.2.0)
#>  evaluate      0.21    2023-05-05 [3] RSPM (R 4.2.0)
#>  fastmap       1.1.1   2023-02-24 [3] RSPM (R 4.2.0)
#>  fs            1.6.3   2023-07-20 [3] RSPM (R 4.2.0)
#>  glue          1.6.2   2022-02-24 [3] RSPM (R 4.2.0)
#>  htmltools     0.5.6   2023-08-10 [3] RSPM (R 4.2.0)
#>  knitr         1.44    2023-09-11 [3] RSPM (R 4.3.0)
#>  lifecycle     1.0.3   2022-10-07 [3] RSPM (R 4.2.0)
#>  magrittr      2.0.3   2022-03-30 [3] RSPM (R 4.2.0)
#>  processx      3.8.2   2023-06-30 [3] RSPM (R 4.2.0)
#>  ps            1.7.5   2023-04-18 [3] RSPM (R 4.3.0)
#>  purrr         1.0.2   2023-08-10 [3] RSPM (R 4.2.0)
#>  R.cache       0.16.0  2022-07-21 [3] RSPM (R 4.2.0)
#>  R.methodsS3   1.8.2   2022-06-13 [3] RSPM (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [3] RSPM (R 4.2.0)
#>  R.utils       2.12.2  2022-11-11 [3] RSPM (R 4.2.0)
#>  R6            2.5.1   2021-08-19 [3] RSPM (R 4.2.0)
#>  reprex        2.0.2   2022-08-17 [3] RSPM (R 4.2.0)
#>  rlang         1.1.1   2023-04-28 [3] RSPM (R 4.2.0)
#>  rmarkdown     2.25    2023-09-18 [3] RSPM (R 4.3.0)
#>  rstudioapi    0.15.0  2023-07-07 [3] RSPM (R 4.2.0)
#>  sessioninfo   1.2.2   2021-12-06 [3] RSPM (R 4.2.0)
#>  styler        1.10.2  2023-08-29 [3] RSPM (R 4.2.0)
#>  vctrs         0.6.3   2023-06-14 [3] RSPM (R 4.2.0)
#>  withr         2.5.0   2022-03-03 [3] RSPM (R 4.2.0)
#>  xfun          0.40    2023-08-09 [3] RSPM (R 4.2.0)
#>  yaml          2.3.7   2023-01-23 [3] RSPM (R 4.2.0)
#> 
#>  [1] /home/floris/lib/R/library
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by florisvdh** [comment] 2023-09-20 15:53
Well actually I think the next step goes wrong in your situation.

That is:

`result_parsed <- jsonlite::fromJSON(result$stdout)`

So please run 

```r
result <- withr::with_envvar(
  c(QT_QPA_PLATFORM="offscreen"), 
  processx::run("qgis_process", c("list", "--json"), encoding = "UTF-8")
)
str(result)
result_parsed <- jsonlite::fromJSON(result$stdout)
str(result_parsed, 2)
```

and we should find out what is needed to get that working.

Example output:

``` r
result <- withr::with_envvar(
  c(QT_QPA_PLATFORM="offscreen"), 
  processx::run("qgis_process", c("list", "--json"), encoding = "UTF-8")
)
str(result)
#> List of 4
#>  $ status : int 0
#>  $ stdout : chr "{\n  \"gdal_version\": \"3.6.4\",\n  \"geos_version\": \"3.11.1-CAPI-1.17.1\",\n  \"proj_version\": \"Rel. 9.1."| __truncated__
#>  $ stderr : chr ""
#>  $ timeout: logi FALSE
result_parsed <- jsonlite::fromJSON(result$stdout)
str(result_parsed, 2)
#> List of 8
#>  $ gdal_version      : chr "3.6.4"
#>  $ geos_version      : chr "3.11.1-CAPI-1.17.1"
#>  $ proj_version      : chr "Rel. 9.1.1, December 1st, 2022"
#>  $ providers         :List of 17
#>   ..$ 3d              :List of 12
#>   ..$ cartographytools:List of 12
#>   ..$ gdal            :List of 12
#>   ..$ grass7          :List of 12
#>   ..$ latlontools     :List of 12
#>   ..$ model           :List of 12
#>   ..$ native          :List of 12
#>   ..$ otb             :List of 12
#>   ..$ pcraster        :List of 12
#>   ..$ pdal            :List of 12
#>   ..$ project         :List of 12
#>   ..$ qgis            :List of 12
#>   ..$ qneat3          :List of 12
#>   ..$ sagang          :List of 12
#>   ..$ script          :List of 12
#>   ..$ visibility      :List of 12
#>   ..$ wbt             :List of 12
#>  $ python_version    : chr "3.10.12"
#>  $ qgis_code_revision: chr "67d46100b5"
#>  $ qgis_version      : chr "3.32.3-Lima"
#>  $ qt_version        : chr "5.15.3"
```

<sup>Created on 2023-09-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.1 (2023-06-16)
#>  os       Linux Mint 21.2
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language nl_BE:nl
#>  collate  nl_BE.UTF-8
#>  ctype    nl_BE.UTF-8
#>  tz       Europe/Brussels
#>  date     2023-09-20
#>  pandoc   3.1.1 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.1   2023-03-23 [3] RSPM (R 4.2.0)
#>  digest        0.6.33  2023-07-07 [3] RSPM (R 4.2.0)
#>  evaluate      0.21    2023-05-05 [3] RSPM (R 4.2.0)
#>  fastmap       1.1.1   2023-02-24 [3] RSPM (R 4.2.0)
#>  fs            1.6.3   2023-07-20 [3] RSPM (R 4.2.0)
#>  glue          1.6.2   2022-02-24 [3] RSPM (R 4.2.0)
#>  htmltools     0.5.6   2023-08-10 [3] RSPM (R 4.2.0)
#>  jsonlite      1.8.7   2023-06-29 [3] RSPM (R 4.2.0)
#>  knitr         1.44    2023-09-11 [3] RSPM (R 4.3.0)
#>  lifecycle     1.0.3   2022-10-07 [3] RSPM (R 4.2.0)
#>  magrittr      2.0.3   2022-03-30 [3] RSPM (R 4.2.0)
#>  processx      3.8.2   2023-06-30 [3] RSPM (R 4.2.0)
#>  ps            1.7.5   2023-04-18 [3] RSPM (R 4.3.0)
#>  purrr         1.0.2   2023-08-10 [3] RSPM (R 4.2.0)
#>  R.cache       0.16.0  2022-07-21 [3] RSPM (R 4.2.0)
#>  R.methodsS3   1.8.2   2022-06-13 [3] RSPM (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [3] RSPM (R 4.2.0)
#>  R.utils       2.12.2  2022-11-11 [3] RSPM (R 4.2.0)
#>  R6            2.5.1   2021-08-19 [3] RSPM (R 4.2.0)
#>  reprex        2.0.2   2022-08-17 [3] RSPM (R 4.2.0)
#>  rlang         1.1.1   2023-04-28 [3] RSPM (R 4.2.0)
#>  rmarkdown     2.25    2023-09-18 [3] RSPM (R 4.3.0)
#>  rstudioapi    0.15.0  2023-07-07 [3] RSPM (R 4.2.0)
#>  sessioninfo   1.2.2   2021-12-06 [3] RSPM (R 4.2.0)
#>  styler        1.10.2  2023-08-29 [3] RSPM (R 4.2.0)
#>  vctrs         0.6.3   2023-06-14 [3] RSPM (R 4.2.0)
#>  withr         2.5.0   2022-03-03 [3] RSPM (R 4.2.0)
#>  xfun          0.40    2023-08-09 [3] RSPM (R 4.2.0)
#>  yaml          2.3.7   2023-01-23 [3] RSPM (R 4.2.0)
#> 
#>  [1] /home/floris/lib/R/library
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by florisvdh** [comment] 2023-09-20 16:46
Going ± offline now, but the JSON parsing is the thing to be fixed. Maybe we can improve that in {qgisprocess}, maybe it's something to be looked at by QGIS or {jsonlite} devs.

Anyway I'm curious whether I could reproduce it here with your JSON file.

**Comment by florisvdh** [comment] 2023-09-21 14:54
> There seems to be a missing parenthesis at the end of the file.

Yes, well spotted. The end is like this, so it misses both a closing double quote and a curly brace:

```
  "python_version": "3.8.10",
  "qgis_code_revision": "65e4edfdad",
  "qgis_version": "3.26.3-Buenos Aires",
  "qt_version": "5.1
```

that gives

```r
> result_parsed <- jsonlite::fromJSON("jsonstring.txt")
Error in parse_con(txt, bigint_as_char) : parse error: premature EOF
                                       
                     (right here) ------^
```

It should become

```
  "python_version": "3.8.10",
  "qgis_code_revision": "65e4edfdad",
  "qgis_version": "3.26.3-Buenos Aires",
  "qt_version": "5.1"
}
```

which then gives:

```r
> result_parsed <- jsonlite::fromJSON("jsonstring.txt")
str(result_parsed, 2)
List of 8
 $ gdal_version      : chr "3.4.3"
 $ geos_version      : chr "3.10.2-CAPI-1.16.0"
 $ proj_version      : chr "Rel. 8.2.0, November 1st, 2021"
 $ providers         :List of 7
  ..$ 3d     :List of 12
  ..$ gdal   :List of 12
  ..$ model  :List of 12
  ..$ native :List of 12
  ..$ project:List of 12
  ..$ qgis   :List of 12
  ..$ script :List of 12
 $ python_version    : chr "3.8.10"
 $ qgis_code_revision: chr "65e4edfdad"
 $ qgis_version      : chr "3.26.3-Buenos Aires"
 $ qt_version        : chr "5.1"

```

**Comment by florisvdh** [comment] 2023-09-21 15:22
I don't know why it's happening on your system. The JSON string is generated by `qgis_process` itself. AFAIK QGIS 3.26 did this OK on Win/macOS/Ubuntu; perhaps some system-specific feature/setting in your case may be at stake which makes QGIS (= including `qgis_process`) misbehave.

You could report it at the QGIS repo, restricting the problem to `qgis_process` itself (R is not involved), and well documenting the setup in which you encounter this (so that they can reproduce).

However before doing that, I'd advise you to try out a current QGIS release, and perhaps use Ubuntu 22.04 if it is an option since current QGIS (3.32) is readily available for Ubuntu 22.04 (using analogous PPA + QGIS repo setup; you have done that well). The problem may have been tackled already, but will not be backported to 3.26 as it that one is not supported anymore (so then it is a solved issue already).

In the meantime, for your current setup, you can:

- install {qgisprocess} from this repo (with `remotes::install_github()`); it now has some protection against soft configuration failures like yours (see PR [#177](https://github.com/r-spatial/qgisprocess/pull/177)). After the PR is merged (could happen very soon), you can also install this version with `install.packages("qgisprocess", repos = c("https://r-spatial.r-universe.dev", "https://cloud.r-project.org"))` once version `0.1.0.9177` is present at https://r-spatial.r-universe.dev. Even though this version does not solve all problems (e.g. `qgis_algorithms()` not working), it can at least do other things that don't need `qgis_algorithms()`.
- just continue using your setup and version 0.1.0, but using legacy behaviour, i.e. not using JSON strings at all. This somehow limits possibilities (but most should work OK) and we may at one point abandon this approach, but not in the near future. To do this, run following line _before_ loading {qgisprocess}:

`options(qgisprocess.use_json_input = FALSE, qgisprocess.use_json_output = FALSE)`

**Comment by florisvdh** [comment] 2023-09-22 08:37
Thanks for follow-up and for trying Ubuntu 22.04 + current QGIS!

> I have no way to access their bug reporting system (or at least have found no way to do it).

It is https://github.com/qgis/QGIS/issues/new/choose, anyone can use it.

I forgot that you should have prepended again with `QT_QPA_PLATFORM="offscreen"`.

Can you just run below code please and report the result. (Above I also pasted the resulting output on my system for comparison, don't copy-paste that part.)

```bash
QT_QPA_PLATFORM="offscreen" qgis_process list --json | tail -5
```

**Comment by florisvdh** [comment] 2023-09-22 10:07
Thanks a lot; that is the confirmation we needed.

> I have changed the permissions accordingly

Aha... I expect this should solve the problem in R then!

**Comment by florisvdh** [comment] 2023-09-22 10:43
Can you verify that `stderr` in output of `str(result)` is empty now? I'm referring to the code in https://github.com/r-spatial/qgisprocess/issues/176#issuecomment-1727998390.

**Comment by florisvdh** [comment] 2023-09-22 11:17
> Is there a way I can use the plugin without cache enabled?

This issue did inspire me to add some protection in loading the package during startup, in order to prevent it from ending prematurely and resulting in an empty cache. That's work mostly complete by now in PR #177, you may give it a try.

However 'not caching' would not help, since your problem is in the communication with `qgis_process`, at least for running things like `qgis_algorithms()`, `qgis_providers()` and probably more.

A possible alternative is to not use JSON input/output in {qgisprocess}; see https://github.com/r-spatial/qgisprocess/issues/176#issuecomment-1729803887.

==> Nevertheless you should find out why you still have a problem currently, after fixing the file permission which seemed to fix the JSON string! Perhaps the file permission is not persistent, e.g. if this folder `/home/stsinc/tmp` is recreated each time? That would be my first guess.

**Comment by florisvdh** [comment] 2023-09-22 13:01
OK, thanks. Can you again set `XDG_RUNTIME_DIR=/home/stsinc/tmp` in `~/.bashrc` as you probably did in https://github.com/r-spatial/qgisprocess/issues/176#issuecomment-1727925676? And set the permission of `/home/stsinc/tmp` to `0700`? Then start a new shell session before launching R and {qgisprocess}, so that the `XDG_RUNTIME_DIR` variable is loaded.

**Comment by florisvdh** [comment] 2023-09-22 13:15
Thanks!

> Maybe character encoding is the culprit?

Everything should be UTF-8 by default in `processx::run()`, I don't think that's the problem here. It still seems like the JSON string missed the final characters. However you may try by dropping `options(encoding = "native.enc")` in both `Rprofile.*` files.

So now my questions for the new state are:

- can you load {qgisprocess}? Either 0.1.0 or 0.1.9177, shouldn't matter.
- if not, are the double quote and curly brace still lacking if you write a newly made `result` object (made as in https://github.com/r-spatial/qgisprocess/issues/176#issuecomment-1727998390) to a `jsonstring.txt` file? (`cat(result$stdout, file = "jsonstring.txt")`). Also check that `result$stderr` is still empty.
- if double quote and curly brace are effectively included, then verify that `result_parsed <- jsonlite::fromJSON(result$stdout)` works. If it doesn't, it means that the missing final characters in the JSON string weren't the only problem.

**Comment by florisvdh** [comment] 2023-09-22 13:20
> If it doesn't, it means that the missing final characters in the JSON string weren't the only problem.

However when I used your first (malformed) `jsonstring.txt` file I could effectively reproduce your problem with `jsonlite::fromJSON()` and make it work after adding the final two characters (https://github.com/r-spatial/qgisprocess/issues/176#issuecomment-1729751615), so I don't believe the encoding is at stake here.

So I do believe it's about those characters, and you already hit the solution I think.

**Comment by florisvdh** [comment] 2023-09-22 13:22
BTW the 'NO carriage return after the last curly brace' (https://github.com/r-spatial/qgisprocess/issues/176#issuecomment-1731158144)  is normal and shouldn't be the problem.

**Comment by florisvdh** [comment] 2023-09-22 13:35
Thanks for pursuing this.

Indeed the XDG error still needs more attention; from what we've seen it causes the trouble.

You can also set `XDG_RUNTIME_DIR` specifically for R if you like, in `~/.Renviron` (text file with line `XDG_RUNTIME_DIR="/home/..."`, read and set by R when it launches). However the `.bashrc` approach is better since it also applies when calling `qgis_process` directly in a shell.

**Comment by florisvdh** [comment] 2023-09-22 13:57
> now it works all the time

Including {qgisprocess} I assume?

> Do you think I should add a bug report about `qgis_process`

No, because the XDG Base Directory Specification (`XDG_RUNTIME_DIR` being set) is not tied to QGIS; it is tied to your system as I understand it. So your solution just satisfies a need that `qgis_process` has, but also various other programs, I expect. It demonstrates that your Ubuntu 22.04 setup is different from most (I think). Normally this variable is just pre-set already (see also https://askubuntu.com/questions/872792/what-is-xdg-runtime-dir for more info). Here I get:

```bash
$ echo $XDG_RUNTIME_DIR
/run/user/1000
```

Anyway it is good to have this documented here, so that future users can find this too.

**Comment by florisvdh** [comment] 2023-09-22 14:10
@asitemade4u can you confirm `library(qgisprocess)` is now working? Then this issue can be closed.

**Comment by florisvdh** [comment] 2023-09-22 14:13
> > Including {qgisprocess} I assume?
> 
> Nope, still behaving the same. And when executing `qgis_configure()` I get our old foe:
> 
> ```shell
> 1 out of 3 available processing provider plugins are enabled.
> parse error: premature EOF
>                                        {   "gdal_version": "3.4.3",   
>                      (right here) ------^
> ```

So then you probably still have the XDG stderr too, as in your https://github.com/r-spatial/qgisprocess/issues/176#issuecomment-1731420858?

**Comment by florisvdh** [comment] 2023-09-22 14:15
> It does not complain, so I assume it works ;o))

Well, `library(qgisprocess)` will only work if `qgis_process` predictably emits correct JSON strings, its seems that is the problem anyway. I advise you to make a QGIS issue indeed, as stated in above https://github.com/r-spatial/qgisprocess/issues/176#issuecomment-1731490429.

**Comment by florisvdh** [comment] 2023-09-22 14:16
`library(qgisprocess)` does not complain: also after restarting R?

**Comment by florisvdh** [comment] 2023-09-22 14:22
Sidenote: rerunning `library(qgisprocess)` in the same R session after it was already loaded a first time, will never return anything, as its loading will be skipped.

**Comment by florisvdh** [comment] 2023-09-22 14:38
OK thanks.

In conclusion:

- post the QGIS issue demonstrating the effect of `XDG_RUNTIME_DIR` along with your system setup (*)
- try to figure out how to get rid of this 'XDG_RUNTIME_DIR not set' warning on your system, as it appears to be tied to the corrupt JSON. R package {qgisprocess} cannot solve this for you, so closing here, but you're welcome to post further updates on your problem.

(*) however a missing `XDG_RUNTIME_DIR` does not harm the JSON string I get on my system; even though I do get the warning in such case:

```bash
$ QT_QPA_PLATFORM="offscreen" XDG_RUNTIME_DIR="" qgis_process list --json | tail -5
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-floris'
  "python_version": "3.10.12",
  "qgis_code_revision": "67d46100b5",
  "qgis_version": "3.32.3-Lima",
  "qt_version": "5.15.3"
}
```

But if _you_ can reproduce the contrasting behaviours in the shell (see https://github.com/r-spatial/qgisprocess/issues/176#issuecomment-1731490429), then that's a good starting point for an issue at QGIS!

**Closed by florisvdh** 2023-09-22 14:38 UTC
